version: '3.7'
services:
  discovery-server:
    image: microservices-tutorial/discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  ## MySQL Service Configuration
  mysql:
    image: mysql:latest  # Corrected the typo
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql  # Set a root password
      MYSQL_PASSWORD: mysql  # Password for the non-root user
    volumes:
      - mysql_data:/var/lib/mysql  # Persistent volume for MySQL data

  ## Order-Service Docker Compose Config
  order-service:
    image: microservices-tutorial/order-service:latest
    container_name: order-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  mysql_data:
